name: Convert to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'docs/**.md'
      - 'docs/images/**'
      - 'docs/styles/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: docs
          output_dir: pdfs
          images_dir: docs/images
          image_import: ./images
          build_html: false
          theme: docs/styles/theme.css
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs

# Taken from: https://github.com/marketplace/actions/markdown-to-pdf-and-html
